[server]
name = "mcrizzledizzle default"
motd = "For shits and giggles"
port = 25565

[world]
world = "world.wrld" # Custom world type, not interchangable
# Generation parameters, when a world is read these are ignored
size_x = 64
size_y = 32
size_z = 64
