[server]
name = "mcrizzledizzle default"
motd = "For shits and giggles"
port = 25565
max_players = 3

[world]
world = "world.wrld" # Custom world type, not interchangable with other servers
# Generation parameters, when a world is read these are ignored
size_x = 64
size_y = 32
size_z = 64
